/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package math.tree

val DEFAULT_EXPRESSION = Add(Scalar(3), Multiply(Scalar(5), Scalar(4)))

class FactoryFunction(val expression: Expression = DEFAULT_EXPRESSION) {
    fun evaluate(): Int {
        return expression.compute()
    }
}

interface Expression {
    fun compute(): Int
}

class Scalar(val value: Int) : Expression {
    override fun compute(): Int {
        return value
    }
}

class Add(val addend: Expression, val addend2: Expression): Expression{
    override fun compute(): Int {
        return addend.compute() + addend2.compute()
    }

}
class Multiply(val multiplier: Expression, val multiplicand: Expression): Expression {
    override fun compute(): Int {
        return multiplier.compute() * multiplicand.compute()
    }
}

fun main(args: Array<String>) {
    println(FactoryFunction().evaluate())
}
