/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package math.tree

val DEFAULT_EXPRESSION = Add(Scalar(3), Multiply(Scalar(5), Scalar(4)))

class FactoryFunction(val expression: Expression = DEFAULT_EXPRESSION) {
    fun evaluate(): Int {
        return expression.compute()
    }
}

/**
 * Expression interface for integer arithmetic
 */
interface Expression {
    /**
     * Computes the value of the expression
     */
    fun compute(): Int
}

/**
 * Object holding a single integer
 */
class Scalar(private val value: Int) : Expression {
    override fun compute(): Int {
        return value
    }
}

/**
 * @param augend Number that is to be added to
 * @param addend Number to add to the [augend]
 */
class Add(private val augend: Expression, private val addend: Expression): Expression{
    override fun compute(): Int {
        return augend.compute() + addend.compute()
    }
}

/**
 * Evaluates multiplication of two Integer Expressions
 * @param multiplier number to be multiplied
 * @param multiplicand number to be multiplied by another
 */
class Multiply(private val multiplier: Expression, private val multiplicand: Expression): Expression {
    override fun compute(): Int {
        return multiplier.compute() * multiplicand.compute()
    }
}

fun main(args: Array<String>) {
    println(FactoryFunction().evaluate())
}
